var prods = [
    {
        "id": "1",
        "category": "sneakers",
        "brand" : "nike",
        "size": "42",
        "color" : "white",
        "price" : "300",
        "rank": "1",
        "image": "images/nike_193145374591_images_13037148081.jpg",
        "title": "Prod 1",
        "gender": "male"
    },
    {
        "id": "2",
        "category": "sneakers",
        "brand" : "reebok",
        "size": "42",
        "color" : "black",
        "price" : "350",
        "rank": "2",
        "image": "images/nike_191885439693_images_13037382429.jpg",
        "title": "Prod 2",
        "gender": "male"
    },
    {
        "id": "3",
        "category": "sneakers",
        "brand" : "nike",
        "size": "42",
        "color" : "red",
        "price" : "250",
        "rank": "2",
        "image": "images/nike_193145374928_images_13375749410.jpg",
        "title": "Prod 3",
        "gender": "female"
    },
    {
        "id": "4",
        "category": "sneakers",
        "brand" : "adidas",
        "size": "44",
        "color" : "blue",
        "price" : "450",
        "rank": "3",
        "image": "images/adidas_4061616434036_images_14038924434.jpg",
        "title": "Prod 4",
        "gender": "male"
    },
    {
        "id": "5",
        "category": "sneakers",
        "brand" : "adidas",
        "size": "41",
        "color" : "red",
        "price" : "120",
        "rank": "222",
        "image": "images/adidas_4060509421665_images_10657020116.jpg",
        "title": "Prod 5",
        "gender": "female"
    },
    {
        "id": "6",
        "category": "t-shirts",
        "brand" : "lacoste",
        "size": "l",
        "color" : "blue",
        "price" : "50",
        "rank": "26",
        "image": "images/lacoste_2000003282449_images_10295960457.jpg",
        "title": "Prod 6",
        "gender": "male"
    },
    {
        "id": "7",
        "category": "t-shirts",
        "brand" : "nike",
        "size": "s",
        "color" : "white",
        "price" : "14",
        "rank": "1226",
        "image": "images/nike_191888631544_images_10269473349.jpg",
        "title": "Prod 7",
        "gender": "male"
    },
    {
        "id": "8",
        "category": "t-shirts",
        "brand" : "nike",
        "size": "xl",
        "color" : "green",
        "price" : "15",
        "rank": "126",
        "image": "images/nike_191888631605_images_10269474375.jpg",
        "title": "Prod 8",
        "gender": "male"
    },
    {
        "id": "9",
        "category": "caps",
        "brand" : "47 Brand",
        "color" : "black",
        "price" : "34.99",
        "rank": "1226",
        "image": "images/liverpool-exclusive-metallic-black-black-snapback-47-brand.jpg",
        "title": "Prod 9",
        "gender": "male",
        "shape": "snapback"
    },
    {
        "id": "10",
        "category": "caps",
        "brand" : "adidas",
        "color" : "red",
        "price" : "27.99",
        "rank": "26",
        "image": "images/new-york-rangers-flat-brim-red-navy-snapback-adidas.jpg",
        "title": "Prod 10",
        "gender": "female"
    },
    {
        "id": "11",
        "category": "bags",
        "brand" : "adidas",
        "color" : "green",
        "price" : "17.99",
        "occasion": "work",
        "size": "medium",
        "rank": "26",
        "material": "hunter leather",
        "image": "images/rBVaSVtDSJeAULLYAAHsEW3bJhw614.jpg",
        "title": "Prod 11",
        "gender": "male"
    },
    {
        "id": "12",
        "category": "bag",
        "brand" : "lv",
        "color" : "white",
        "price" : "123.99",
        "occasion": "work",
        "size": "medium",
        "rank": "226",
        "material": "hunter leather",
        "image": "images/bag.png",
        "title": "Prod 12",
        "gender": "male"
    },
    {
        "id": "13",
        "category": "cap",
        "brand" : "nike",
        "color" : "black",
        "price" : "17.99",
        "occasion": "travel",
        "size": "medium",
        "rank": "26",
        "material": "hunter leather",
        "image": "images/cap.png",
        "title": "Prod 13",
        "gender": "male"
    },
    {
        "id": "14",
        "category": "sneakers",
        "brand" : "adidas",
        "color" : "white",
        "price" : "172.99",
        "size": "43",
        "rank": "26",
        "image": "images/sneakers.png",
        "title": "Prod 14",
        "gender": "male"
    },
    {
        "id": "15",
        "category": "t-shirts",
        "brand" : "adidas",
        "color" : "white",
        "price" : "7.99",
        "size": "m",
        "rank": "26",
        "image": "images/t-shirt.png",
        "title": "Prod 15",
        "gender": "male"
    },
    {
        "id": "16",
        "category": "sneakers",
        "brand" : "nike",
        "size": "42",
        "color" : "white",
        "price" : "300",
        "rank": "1",
        "image": "images/nike_193145374591_images_13037148081.jpg",
        "title": "Prod 16",
        "gender": "male"
    },
    {
        "id": "17",
        "category": "sneakers",
        "brand" : "reebok",
        "size": "42",
        "color" : "black",
        "price" : "350",
        "rank": "2",
        "image": "images/nike_191885439693_images_13037382429.jpg",
        "title": "Prod 17",
        "gender": "male"
    },
    {
        "id": "18",
        "category": "sneakers",
        "brand" : "nike",
        "size": "42",
        "color" : "red",
        "price" : "250",
        "rank": "2",
        "image": "images/nike_193145374928_images_13375749410.jpg",
        "title": "Prod 18",
        "gender": "female"
    },
    {
        "id": "19",
        "category": "sneakers",
        "brand" : "adidas",
        "size": "44",
        "color" : "blue",
        "price" : "450",
        "rank": "3",
        "image": "images/adidas_4061616434036_images_14038924434.jpg",
        "title": "Prod 19",
        "gender": "male"
    },
    {
        "id": "20",
        "category": "sneakers",
        "brand" : "adidas",
        "size": "41",
        "color" : "red",
        "price" : "120",
        "rank": "222",
        "image": "images/adidas_4060509421665_images_10657020116.jpg",
        "title": "Prod 20",
        "gender": "female"
    },
    {
        "id": "21",
        "category": "t-shirts",
        "brand" : "lacoste",
        "size": "l",
        "color" : "blue",
        "price" : "50",
        "rank": "26",
        "image": "images/lacoste_2000003282449_images_10295960457.jpg",
        "title": "Prod 21",
        "gender": "male"
    },
    {
        "id": "22",
        "category": "t-shirts",
        "brand" : "nike",
        "size": "s",
        "color" : "white",
        "price" : "14",
        "rank": "1226",
        "image": "images/nike_191888631544_images_10269473349.jpg",
        "title": "Prod 22",
        "gender": "male"
    },
    {
        "id": "23",
        "category": "t-shirts",
        "brand" : "nike",
        "size": "xl",
        "color" : "green",
        "price" : "15",
        "rank": "126",
        "image": "images/nike_191888631605_images_10269474375.jpg",
        "title": "Prod 23",
        "gender": "male"
    },
    {
        "id": "24",
        "category": "caps",
        "brand" : "47 Brand",
        "color" : "black",
        "price" : "34.99",
        "rank": "1226",
        "image": "images/liverpool-exclusive-metallic-black-black-snapback-47-brand.jpg",
        "title": "Prod 24",
        "gender": "male",
        "shape": "snapback"
    },
    {
        "id": "25",
        "category": "caps",
        "brand" : "adidas",
        "color" : "red",
        "price" : "27.99",
        "rank": "26",
        "image": "images/new-york-rangers-flat-brim-red-navy-snapback-adidas.jpg",
        "title": "Prod 25",
        "gender": "female"
    },
    {
        "id": "26",
        "category": "bags",
        "brand" : "adidas",
        "color" : "green",
        "price" : "17.99",
        "occasion": "work",
        "size": "medium",
        "rank": "26",
        "material": "hunter leather",
        "image": "images/rBVaSVtDSJeAULLYAAHsEW3bJhw614.jpg",
        "title": "Prod 26",
        "gender": "male"
    },
    {
        "id": "27",
        "category": "bag",
        "brand" : "lv",
        "color" : "white",
        "price" : "123.99",
        "occasion": "work",
        "size": "medium",
        "rank": "226",
        "material": "hunter leather",
        "image": "images/bag.png",
        "title": "Prod 27",
        "gender": "male"
    },
    {
        "id": "28",
        "category": "cap",
        "brand" : "nike",
        "color" : "black",
        "price" : "17.99",
        "occasion": "travel",
        "size": "medium",
        "rank": "26",
        "material": "hunter leather",
        "image": "images/cap.png",
        "title": "Prod 28",
        "gender": "male"
    },
    {
        "id": "29",
        "category": "sneakers",
        "brand" : "adidas",
        "color" : "white",
        "price" : "172.99",
        "size": "43",
        "rank": "26",
        "image": "images/sneakers.png",
        "title": "Prod 29",
        "gender": "male"
    },
    {
        "id": "30",
        "category": "t-shirts",
        "brand" : "adidas",
        "color" : "white",
        "price" : "7.99",
        "size": "m",
        "rank": "26",
        "image": "images/t-shirt.png",
        "title": "Prod 30",
        "gender": "male"
    },






    {
        "id": "31",
        "category": "sneakers",
        "brand" : "nike",
        "size": "42",
        "color" : "white",
        "price" : "300",
        "rank": "1",
        "image": "images/nike_193145374591_images_13037148081.jpg",
        "title": "Prod 31",
        "gender": "male"
    },
    {
        "id": "32",
        "category": "sneakers",
        "brand" : "reebok",
        "size": "42",
        "color" : "black",
        "price" : "350",
        "rank": "2",
        "image": "images/nike_191885439693_images_13037382429.jpg",
        "title": "Prod 32",
        "gender": "male"
    },
    {
        "id": "33",
        "category": "sneakers",
        "brand" : "nike",
        "size": "42",
        "color" : "red",
        "price" : "250",
        "rank": "2",
        "image": "images/nike_193145374928_images_13375749410.jpg",
        "title": "Prod 33",
        "gender": "female"
    },
    {
        "id": "34",
        "category": "sneakers",
        "brand" : "adidas",
        "size": "44",
        "color" : "blue",
        "price" : "450",
        "rank": "3",
        "image": "images/adidas_4061616434036_images_14038924434.jpg",
        "title": "Prod 34",
        "gender": "male"
    },
    {
        "id": "35",
        "category": "sneakers",
        "brand" : "adidas",
        "size": "41",
        "color" : "red",
        "price" : "120",
        "rank": "222",
        "image": "images/adidas_4060509421665_images_10657020116.jpg",
        "title": "Prod 35",
        "gender": "female"
    },
    {
        "id": "36",
        "category": "t-shirts",
        "brand" : "lacoste",
        "size": "l",
        "color" : "blue",
        "price" : "50",
        "rank": "26",
        "image": "images/lacoste_2000003282449_images_10295960457.jpg",
        "title": "Prod 36",
        "gender": "male"
    },
    {
        "id": "37",
        "category": "t-shirts",
        "brand" : "nike",
        "size": "s",
        "color" : "white",
        "price" : "14",
        "rank": "1226",
        "image": "images/nike_191888631544_images_10269473349.jpg",
        "title": "Prod 37",
        "gender": "male"
    },
    {
        "id": "38",
        "category": "t-shirts",
        "brand" : "nike",
        "size": "xl",
        "color" : "green",
        "price" : "15",
        "rank": "126",
        "image": "images/nike_191888631605_images_10269474375.jpg",
        "title": "Prod 38",
        "gender": "male"
    },
    {
        "id": "39",
        "category": "caps",
        "brand" : "47 Brand",
        "color" : "black",
        "price" : "34.99",
        "rank": "1226",
        "image": "images/liverpool-exclusive-metallic-black-black-snapback-47-brand.jpg",
        "title": "Prod 39",
        "gender": "male",
        "shape": "snapback"
    },
    {
        "id": "40",
        "category": "caps",
        "brand" : "adidas",
        "color" : "red",
        "price" : "27.99",
        "rank": "26",
        "image": "images/new-york-rangers-flat-brim-red-navy-snapback-adidas.jpg",
        "title": "Prod 40",
        "gender": "female"
    },
    {
        "id": "41",
        "category": "bags",
        "brand" : "adidas",
        "color" : "green",
        "price" : "17.99",
        "occasion": "work",
        "size": "medium",
        "rank": "26",
        "material": "hunter leather",
        "image": "images/rBVaSVtDSJeAULLYAAHsEW3bJhw614.jpg",
        "title": "Prod 41",
        "gender": "male"
    },
    {
        "id": "42",
        "category": "bag",
        "brand" : "lv",
        "color" : "white",
        "price" : "123.99",
        "occasion": "work",
        "size": "medium",
        "rank": "226",
        "material": "hunter leather",
        "image": "images/bag.png",
        "title": "Prod 42",
        "gender": "male"
    },
    {
        "id": "43",
        "category": "cap",
        "brand" : "nike",
        "color" : "black",
        "price" : "17.99",
        "occasion": "travel",
        "size": "medium",
        "rank": "26",
        "material": "hunter leather",
        "image": "images/cap.png",
        "title": "Prod 43",
        "gender": "male"
    },
    {
        "id": "44",
        "category": "sneakers",
        "brand" : "adidas",
        "color" : "white",
        "price" : "172.99",
        "size": "43",
        "rank": "26",
        "image": "images/sneakers.png",
        "title": "Prod 44",
        "gender": "male"
    },
    {
        "id": "45",
        "category": "t-shirts",
        "brand" : "adidas",
        "color" : "white",
        "price" : "7.99",
        "size": "m",
        "rank": "26",
        "image": "images/t-shirt.png",
        "title": "Prod 45",
        "gender": "male"
    },
    {
        "id": "46",
        "category": "sneakers",
        "brand" : "nike",
        "size": "42",
        "color" : "white",
        "price" : "300",
        "rank": "1",
        "image": "images/nike_193145374591_images_13037148081.jpg",
        "title": "Prod 46",
        "gender": "male"
    },
    {
        "id": "47",
        "category": "sneakers",
        "brand" : "reebok",
        "size": "42",
        "color" : "black",
        "price" : "350",
        "rank": "2",
        "image": "images/nike_191885439693_images_13037382429.jpg",
        "title": "Prod 47",
        "gender": "male"
    },
    {
        "id": "48",
        "category": "sneakers",
        "brand" : "nike",
        "size": "42",
        "color" : "red",
        "price" : "250",
        "rank": "2",
        "image": "images/nike_193145374928_images_13375749410.jpg",
        "title": "Prod 48",
        "gender": "female"
    },
    {
        "id": "49",
        "category": "sneakers",
        "brand" : "adidas",
        "size": "44",
        "color" : "blue",
        "price" : "450",
        "rank": "3",
        "image": "images/adidas_4061616434036_images_14038924434.jpg",
        "title": "Prod 49",
        "gender": "male"
    },
    {
        "id": "50",
        "category": "sneakers",
        "brand" : "adidas",
        "size": "41",
        "color" : "red",
        "price" : "120",
        "rank": "222",
        "image": "images/adidas_4060509421665_images_10657020116.jpg",
        "title": "Prod 50",
        "gender": "female"
    },
    {
        "id": "51",
        "category": "t-shirts",
        "brand" : "lacoste",
        "size": "l",
        "color" : "blue",
        "price" : "50",
        "rank": "26",
        "image": "images/lacoste_2000003282449_images_10295960457.jpg",
        "title": "Prod 51",
        "gender": "male"
    },
    {
        "id": "52",
        "category": "t-shirts",
        "brand" : "nike",
        "size": "s",
        "color" : "white",
        "price" : "14",
        "rank": "1226",
        "image": "images/nike_191888631544_images_10269473349.jpg",
        "title": "Prod 52",
        "gender": "male"
    },
    {
        "id": "53",
        "category": "t-shirts",
        "brand" : "nike",
        "size": "xl",
        "color" : "green",
        "price" : "15",
        "rank": "126",
        "image": "images/nike_191888631605_images_10269474375.jpg",
        "title": "Prod 53",
        "gender": "male"
    },
    {
        "id": "54",
        "category": "caps",
        "brand" : "47 Brand",
        "color" : "black",
        "price" : "34.99",
        "rank": "1226",
        "image": "images/liverpool-exclusive-metallic-black-black-snapback-47-brand.jpg",
        "title": "Prod 54",
        "gender": "male",
        "shape": "snapback"
    },
    {
        "id": "55",
        "category": "caps",
        "brand" : "adidas",
        "color" : "red",
        "price" : "27.99",
        "rank": "26",
        "image": "images/new-york-rangers-flat-brim-red-navy-snapback-adidas.jpg",
        "title": "Prod 55",
        "gender": "female"
    },
    {
        "id": "56",
        "category": "bags",
        "brand" : "adidas",
        "color" : "green",
        "price" : "17.99",
        "occasion": "work",
        "size": "medium",
        "rank": "26",
        "material": "hunter leather",
        "image": "images/rBVaSVtDSJeAULLYAAHsEW3bJhw614.jpg",
        "title": "Prod 56",
        "gender": "male"
    },
    {
        "id": "57",
        "category": "bag",
        "brand" : "lv",
        "color" : "white",
        "price" : "123.99",
        "occasion": "work",
        "size": "medium",
        "rank": "226",
        "material": "hunter leather",
        "image": "images/bag.png ",
        "title": "Prod 57",
        "gender": "male"
    },
    {
        "id": "58",
        "category": "cap",
        "brand" : "nike",
        "color" : "black",
        "price" : "17.99",
        "occasion": "travel",
        "size": "medium",
        "rank": "26",
        "material": "hunter leather",
        "image": "images/cap.png ",
        "title": "Prod 58",
        "gender": "male"
    },
    {
        "id": "59",
        "category": "sneakers",
        "brand" : "adidas",
        "color" : "white",
        "price" : "172.99",
        "size": "43",
        "rank": "26",
        "image": "images/sneakers.png ",
        "title": "Prod 59",
        "gender": "male"
    },
    {
        "id": "60",
        "category": "t-shirts",
        "brand" : "adidas",
        "color" : "white",
        "price" : "7.99",
        "size": "m",
        "rank": "26",
        "image": "images/t-shirt.png ",
        "title": "Prod 60",
        "gender": "male"
    }
];